/*
 * Aulas professor Maromo.
 */
package tictactoe.view;

import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import tictactoe.utils.Util;

/**
 *
 * @author maromo
 */
public class JVeia extends javax.swing.JFrame {

    public int vez = 0;
    /**
     * Creates new form JVeia
     */
    public JVeia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bt1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        jPanel1.add(bt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 90, 90));

        bt2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        jPanel1.add(bt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 90, 90));

        bt3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });
        jPanel1.add(bt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 90, 90));

        bt4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });
        jPanel1.add(bt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 90, 90));

        bt5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });
        jPanel1.add(bt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 90, 90));

        bt6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });
        jPanel1.add(bt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 90, 90));

        bt7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt7ActionPerformed(evt);
            }
        });
        jPanel1.add(bt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 90, 90));

        bt8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt8ActionPerformed(evt);
            }
        });
        jPanel1.add(bt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 90, 90));

        bt9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt9ActionPerformed(evt);
            }
        });
        jPanel1.add(bt9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 90, 90));

        btNovo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btNovo.setText("Novo Jogo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });
        jPanel1.add(btNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 330, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        // TODO add your handling code here:
        Util.limparBotoes(jPanel1);
        vez = 0;
    }//GEN-LAST:event_btNovoActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        // TODO add your handling code here:
        jogar(evt);
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        // TODO add your handling code here:
        jogar(evt);
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        // TODO add your handling code here:
        jogar(evt);
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        // TODO add your handling code here:
        jogar(evt);
    }//GEN-LAST:event_bt4ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
        // TODO add your handling code here:
        jogar(evt);
    }//GEN-LAST:event_bt5ActionPerformed

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
        // TODO add your handling code here:
        jogar(evt);
    }//GEN-LAST:event_bt6ActionPerformed

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed
        // TODO add your handling code here:
        jogar(evt);
    }//GEN-LAST:event_bt7ActionPerformed

    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
        // TODO add your handling code here:
        jogar(evt);
    }//GEN-LAST:event_bt8ActionPerformed

    private void bt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt9ActionPerformed
        // TODO add your handling code here:
        jogar(evt);
    }//GEN-LAST:event_bt9ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JButton btNovo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void jogar(ActionEvent evt) {
        JButton bj = (JButton) evt.getSource();
        if(!bj.getText().equals("")){ //jogada invalida
            JOptionPane.showMessageDialog(null, "Casa já foi JOGADA");
            return; //cai fora
        }
        vez++; //jogada valida
        if(vez % 2 == 1){
            bj.setText("X");
        }else{
            bj.setText("0");
        }
        verificarVencedor();
        
    }

    private void verificarVencedor() {
        //Verificar coordenadas para o jogador X
        
        if(bt1.getText().equals("X")&& bt2.getText().equals("X") && bt3.getText().equals("X")){
            mensagem("X");
        }
        if(bt4.getText().equals("X")&& bt5.getText().equals("X") && bt6.getText().equals("X")){
            mensagem("X");
        }
        if(bt7.getText().equals("X")&& bt8.getText().equals("X") && bt9.getText().equals("X")){
            mensagem("X");
        }
        if(bt1.getText().equals("X")&& bt4.getText().equals("X") && bt7.getText().equals("X")){
            mensagem("X");
        }
        if(bt2.getText().equals("X")&& bt5.getText().equals("X") && bt8.getText().equals("X")){
            mensagem("X");
        }
        if(bt3.getText().equals("X")&& bt6.getText().equals("X") && bt9.getText().equals("X")){
            mensagem("X");
        }
        if(bt1.getText().equals("X")&& bt5.getText().equals("X") && bt9.getText().equals("X")){
            mensagem("X");
        }
        if(bt3.getText().equals("X")&& bt5.getText().equals("X") && bt7.getText().equals("X")){
            mensagem("X");
        }
        //Verificar coordenadas para o jogador 0
        
        if(bt1.getText().equals("0")&& bt2.getText().equals("0") && bt3.getText().equals("0")){
            mensagem("0");
        }
        if(bt4.getText().equals("0")&& bt5.getText().equals("0") && bt6.getText().equals("0")){
            mensagem("0");
        }
        if(bt7.getText().equals("0")&& bt8.getText().equals("0") && bt9.getText().equals("0")){
            mensagem("0");
        }
        if(bt1.getText().equals("0")&& bt4.getText().equals("0") && bt7.getText().equals("0")){
            mensagem("0");
        }
        if(bt2.getText().equals("0")&& bt5.getText().equals("0") && bt8.getText().equals("0")){
            mensagem("0");
        }
        if(bt3.getText().equals("0")&& bt6.getText().equals("0") && bt9.getText().equals("0")){
            mensagem("0");
        }
        if(bt1.getText().equals("0")&& bt5.getText().equals("0") && bt9.getText().equals("0")){
            mensagem("0");
        }
        if(bt3.getText().equals("0")&& bt5.getText().equals("0") && bt7.getText().equals("0")){
            mensagem("0");
        }
        if(vez==9){
            JOptionPane.showMessageDialog(null, "Deu Véia (EMPATE)");
            btNovoActionPerformed(null);
        }
        
    }

    private void mensagem(String jog) {
        JOptionPane.showMessageDialog(null, "Jogador " + jog + " foi vencedor");
        btNovoActionPerformed(null);
    }
}
